name: Run Tests
on:
  - push
jobs:
  lts-runtime:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['lts/-2', 'lts/-1']
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for 'master' branch
        run: |
          git fetch --all --quiet --prune
          if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
          fi
          [[ -z "$(git branch --all --list master */master)" ]]
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix['node-version'] }}
          cache: 'npm'
      - name: Install dependencies
        run: npm ci      
      - name: JS Tests
        run: npm run test
  current-runtime:
    runs-on: ubuntu-latest
    needs: lts-runtime
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Check for 'master' branch
        run: |
          git fetch --all --quiet --prune
          if [[ -n "$(git branch --all --list master */master)" ]]; then
              echo "A branch named 'master' was found. Please remove it."
              echo "$(git branch --all --list master */master)"
          fi
          [[ -z "$(git branch --all --list master */master)" ]]
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci      
      - name: JS Tests
        run: npm run test:coverage
      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'      
      - name: Install dependencies
        run: npm ci      
      - name: Type Check
        run: npm run typecheck      
      - name: Lint
        run: npm run lint
